### PR TITLE
Configuration of DMZ status and host

### PR DESCRIPTION
**Pull request by nerk**
Adding options to display and enable/disable DMZ and set DMZ host address. This works for my unmodified E3372-153h with these software versions:

```
 "SoftwareVersion": "22.200.15.02.1217"
 "WebUIVersion": "17.100.12.01.1217"
```

### CODE REVIEW

**Comment by kenshaw** [comment]
Hi, this seems to be fine, but could you please rebase the changes (git rebase -i) to make it a single commit? Thanks!

**Comment by nerk** [comment]
@kenshaw Will this work? I'm not exactly sure what I did here...

**Comment by kenshaw** [comment]
Not sure what you did exactly, but typically the rebase commands would look like this:

```sh
go get -u github.com/knq/hilink
cd $GOPATH/src/github.com/knq/hilink
git checkout -b nerk master # checkout master branch named `nerk`
<make changes and commits>
git remote add nerk https://github.com/nerk/hilink.git
<make changes and commits>
git push -u nerk nerk # push nerk branch to nerk remote
git rebase -i origin/master # interactive rebase off master
```

**Comment by kenshaw** [comment]
The ultimate effect / goal of the above it so have only 1 total commit change, instead of multiple commits as in this pull request. If you push those changes back to your own github branch, this pull request will update and will show only 1 commit.

**Comment by kenshaw** [comment]
Hey -- don't worry about it -- this time I just rebased it locally for you and pushed it to master. Please note though that I also updated / ran 'go generate' for the hlcli command, as your documentation didn't match the hlcli docs. As such, you have a conflict in the `nerk` repo copy.

**Comment by nerk** [comment]
Thanks! I think it's time for me to learn some more git.

**Pull request closed without merging**
