### PR TITLE
Working authentication, login, password change and wlan disabling

### PR DESCRIPTION
**Pull request by mliezun**
Based on the python implementation found on this site: [https://blog.hqcodeshop.fi/archives/259-Huawei-E5186-AJAX-API.html](https://blog.hqcodeshop.fi/archives/259-Huawei-E5186-AJAX-API.html)

### CODE REVIEW

**Comment by kenshaw** [comment]
Appreciate the work! I will review and merge if well written.

**Comment by kenshaw** [comment]
@mliezun This should be multiple PRs, but that's ok -- please rebase this as a single commit, and I will add comments on specific changes that need to be made. Specifically, there are some inconsistencies with the rest of the package that need to be addressed, and some odd bits and pieces that are not idiomatic Go.

**Comment by mliezun** [comment]
Great! I'm going to get hands on, and let you know when i'm finished.

**Comment by kenshaw** [comment]
@mliezun I really appreciate your work, but there are a number of non-idiomatic Go changes interspersed throughout your commits. Please separate these into separate PRs, or at minimum, rebase into a single PR, and I'll annotate the PR commits here with what needs to be changed / fixed before I accept it into repository.

**Pull request closed without merging**
